name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build HelloWorldApp.sln --configuration Release
      - name: Pack library
        run: dotnet pack LinearCongruentGenerator/LinearCongruentGenerator.csproj --configuration Release
      - name: Push package to GitHub Packages
        run: |
          dotnet nuget push LinearCongruentGenerator/bin/Release/*.nupkg \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
            --api-key ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: |
          dotnet publish LinearCongruentGenerator.CLI -c Release -r win-x64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=true \
            -p:PublishAot=true \
            -o published
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: published
