name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build
      run: dotnet build HelloWorldApp.sln
    - name: Test
      run: dotnet test HelloWorldApp.sln --verbosity normal
    - name: Publish for Windows
      run: dotnet publish LinearCongruentGenerator.CLI -c Release -r win-x64 --self-contained false
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: lcg-cli-win-x64
        path: LinearCongruentGenerator.CLI/bin/Release/net8.0/win-x64/publish/
